
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javafx.scene.layout.Background;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.ui.RefineryUtilities;
import project_sanwa_new.DataAlert;
import project_sanwa_new.LineChart;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yotsathon
 */
public class AlertBox extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form Alert
     */
    JPanel alertBox;
    JLabel alertText;
    JButton closeButton;
    public AlertBox(String siteName, String areaName, String dragoConnexName, String roomNumber, String mBusID, String date, String time) {
        initComponents();
        alertBox = new JPanel();
        alertBox.setPreferredSize(new Dimension(850, 60));
        alertBox.setBackground(new Color(246,60,77));
        alertBox.setBackground(new Color(166,101,0));
        //alertText = new JLabel("Site : " + siteName + ", Area : " + areaName + " dragoConnexName : " + dragoConnexName + " roomNumber : " + roomNumber + " mBusID : " + mBusID + " dateTime : " + date + "T" + time + "");
        alertText = new JLabel("Site : " + siteName + ", Area : " + areaName + " roomNumber : " + roomNumber + " dateTime : " + date + "T" + time + "");
        alertText.setForeground(Color.white);
        closeButton = new JButton("Close");
        closeButton.setBackground(new java.awt.Color(166, 101, 0));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.addActionListener(this);
        alertBox.add(alertText);
        alertBox.add(closeButton);
        add(alertBox);
        setBackground(new Color(246,60,77));
        setBackground(new Color(166,101,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 255));
        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == closeButton){
            this.setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
