
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import project_sanwa_new.Alert;
import project_sanwa_new.DataAlert;
import project_sanwa_new.ListAlert;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yotsathon
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
        this.setOpaque(false);
        Timer time = new Timer();
        time.schedule(new TimerTask() {
            public void run() {
                Runnable runnable = new Runnable() {
                    public void run() {
                        removeAll();
                        
                        List<DataAlert> listA = ListAlert.getListAlert();
                        System.out.println(listA.size());
                        for (int i = 0; i < listA.size(); i++) {

                            add(new AlertBox(listA.get(i).getSiteName(), listA.get(i).getAreaName(),listA.get(i).getDragoConnexName(),listA.get(i).getRoomNumber(),listA.get(i).getmBusID(),listA.get(i).getDate(),listA.get(i).getTime()));
                            revalidate();
                            repaint();
                        }

                    }
                };
                new Thread(runnable).start();
            }

        }, 0, 1000 * 10);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(924, 768));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
