
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yotsathon
 */
public class ImportBase extends javax.swing.JPanel {

    /**
     * Creates new form ImportBase
     */
    public ImportBase() {
        initComponents();
    }

    private void loadSites() throws IOException {
        URL url;
        BufferedReader in;
        JSONArray jsonArray;
        JSONObject obj_w = null;
        JSONObject obj_e = null;
        try {
            url = new URL("http://dragoservices.azurewebsites.net/api/DragoServices/Owners");
            in = new BufferedReader(new InputStreamReader(url.openStream()));
            String line = in.readLine();
            if (!"[]".equals(line)) {
                jsonArray = new JSONArray(line);
                obj_w = jsonArray.getJSONObject(0);
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(ImportBase.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
