
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import project_sanwa_new.DBSites;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author yotsathon
 */
public class SiteManagement extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form siteList
     */
    DBSites dbS;
    JTable table;
    JPanel edit;
    JButton saveButton;
    JButton canncelButton;
    JTextField description;
    JTextField address;
    DefaultTableModel model;
    int rowTable;

    public SiteManagement() {
        initComponents();
        dbS = new DBSites();
        
        table = new JTable() {
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int rowIndex, int vColIndex) {
                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
                if (rowIndex % 2 == 0 && !isCellSelected(rowIndex, vColIndex)) {
                    c.setBackground(new Color(107, 184, 245));
                } else if (isCellSelected(rowIndex, vColIndex)) {
                    c.setBackground(new Color(0, 176, 255));
                } else {
                    c.setBackground(getBackground());
                }
                return c;
            }

        };
        table.setPreferredScrollableViewportSize(new Dimension(600, 500));
        table.setFillsViewportHeight(true);
        table.addMouseListener(this);
        JScrollPane scrollPane = new JScrollPane(table);
        description = new JTextField("description", 20);
        address = new JTextField("address", 20);
        saveButton = new JButton("Save");
        saveButton.setEnabled(false);
        saveButton.addMouseListener(this);

        edit = new JPanel();
        edit.add(description);
        edit.add(address);
        edit.add(saveButton);
        getDataToTable();
        add(scrollPane, BorderLayout.LINE_START);
        add(edit, BorderLayout.CENTER);

    }

    private void getDataToTable() {
        
        String columnNames[] = {"Site ID", "Site Description", "Address"};
        model = new DefaultTableModel(new Object[0][0], columnNames);
        dbS.connect();
        ResultSet rs = dbS.selectAllSite();
        try {
            while (rs.next()) {
                Object[] obj = {rs.getString("siteID"), rs.getString("description"), rs.getString("address")};
                model.addRow(obj);
            }
            table.setModel(model);
            table.removeColumn(table.getColumnModel().getColumn(0));
        } catch (SQLException ex) {
            Logger.getLogger(SiteManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getSource() == table) {
            saveButton.setEnabled(true);
            rowTable = table.rowAtPoint(e.getPoint());
            description.setText(model.getValueAt(rowTable, 1).toString());
            address.setText(model.getValueAt(rowTable, 2).toString());
        } else if (e.getSource() == saveButton) {
            int rs = dbS.updateSite(model.getValueAt(rowTable, 0).toString(),description.getText(),address.getText());
            if(rs!=0){
                getDataToTable();
                description.setText("");
                address.setText("");
                saveButton.setEnabled(false);
            } 
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
